src/LearningSystem.App/Controllers/SplashController.cs
using LearningSystem.Data;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace LearningSystem.App.Controllers
{
    public class SplashController : Controller
    {
        IUoWLearningSystem db;
        public SplashController(IUoWLearningSystem db)
        {
            this.db = db;
        }

        public ActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "MyAchievements");
            }

            return View();
        }
	}
}

src/LearningSystem.App/Views/Shared/_Confirmation.cshtml
<h1>Thank you for registring!</h1>
<h2>Please go to your e-mail to confirm your registration.</h2>


src/LearningSystem.App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - LearningSystem</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/kendo")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top ">
        <div class="navbar-inner">
            <div class="container">
                @Html.ActionLink("Learning System", "Index", "Splash", new { area = "" }, new { @class = "brand" })

                <ul class="nav nav-collapse">
                    <li>@Html.ActionLink("Find Skills", "Search", "Home", new { area = "" }, null)</li>
                    @if (User.IsInRole("admin"))
                    {
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Skill", "Index", "Skill", new { area = "Administration" }, null)</li>
                                <li>@Html.ActionLink("Lesson", "Index", "Lesson", new { area = "Administration" }, null)</li>
                                <li>@Html.ActionLink("Exercise", "Index", "Exercise", new { area = "Administration" }, null)</li>
                                <li>@Html.ActionLink("Question", "Index", "Question", new { area = "Administration" }, null)</li>
                                <li>@Html.ActionLink("Upload Skill (XML)", "Index", "Upload", new { area = "Administration" }, null)</li>
                            </ul>
                        </li>
                    }
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, null )</li>
                </ul>
                
                @RenderSection("loginSubmenu", required: false)
                @if (Url.RequestContext.RouteData.Values["controller"].ToString() != "Splash")
                {
                    @Html.Partial("_LoginPartial")
                }

            </div>
        </div>
    </div>

    <div class="container main-container">
        @RenderBody()
        <hr />
        <footer>
            <p id="main-footer-p">&copy; @DateTime.Now.Year - Learning System</p>
        </footer>
    </div>


    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/kendo")
    @RenderSection("scripts", required: false)
</body>
</html>