src/LearningSystem.App/ViewModels/LessonViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LearningSystem.App.ViewModels
{
    public class LessonViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int LevelInSkillTree { get; set; }
        public bool IsLearned { get; set; }
    }
}

src/LearningSystem.App/Areas/Administration/Controllers/LessonController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LearningSystem.Models;
using LearningSystem.Data;
using ValidateAntiForgeryTokenAttribute = TeamAzureDragon.Utils.FakeValidateAntiForgeryTokenAttribute;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using TeamAzureDragon.Utils;
using LearningSystem.App.Areas.Administration.ViewModels;
using Newtonsoft.Json;
using System.IO;

namespace LearningSystem.App.Areas.Administration.Controllers
{
    public class LessonController : AdminController
    {
        IUoWLearningSystem db;
        public LessonController(IUoWLearningSystem db)
        {
            this.db = db;
        }

        // GET: /Administration/Skill/
        public ActionResult Index()
        {
            //ViewData["skills"] = db.Skills.All().ToList()
            //            .Select(skill => Misc.SerializeToDictionary(skill,
            //                    path =>
            //                    {
            //                        //if (path == "Skill") return RecursiveSerializationOption.Assign;
            //                        if (path == "SkillId") return RecursiveSerializationOption.Assign;
            //                        if (path == "Name") return RecursiveSerializationOption.Assign;
            //                        return RecursiveSerializationOption.Skip;
            //                    })).ToList();

            //ViewData["requerments"] = db.Lessons.All().ToList()
            //            .Select(lesson => Misc.SerializeToDictionary(lesson,
            //                    path =>
            //                    {
            //                        if (path == "LessonId") return RecursiveSerializationOption.Assign;
            //                        if (path == "SkillId") return RecursiveSerializationOption.Assign;
            //                        if (path == "Name") return RecursiveSerializationOption.Assign;
            //                        return RecursiveSerializationOption.Skip;
            //                    })).ToList(); 

            return View(db.Lessons.All("Skill").ToList());
        }

        // GET: /Administration/Skill/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lesson lesson = db.Lessons.GetById(id.Value);
            if (lesson == null)
            {
                return HttpNotFound();
            }
            return View(lesson);
        }

        public ActionResult GetSkills([DataSourceRequest]DataSourceRequest request)
        {
            var viewModelSkills = db.Skills.All().ToList()
                    .Select(skill => new SkillViewModel().FillViewModel(skill)).ToList();

            //DataSourceResult result = viewModelExercises.ToDataSourceResult(request);

            return Json(viewModelSkills, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetRequirements([DataSourceRequest]DataSourceRequest request)
        {
            var viewModelReqirements = db.Lessons.All().ToList()
                        .Select(requerment => new LessonViewModel().FillViewModel(requerment)).ToList();

            //DataSourceResult result = viewModelExercises.ToDataSourceResult(request);

            return Json(viewModelReqirements, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Read([DataSourceRequest]DataSourceRequest request)
        {
            var viewModelLessons = db.Lessons.All("Skill").ToList()
                .Select(lesson => new LessonViewModel().FillViewModel(lesson)).ToList();

            //for (int i = 0; i < viewModelLessons.Count(); i++)
            //{
            //    if (viewModelLessons[i].Description != null)
            //    {
            //        viewModelLessons[i].Description = viewModelLessons[i].Description.Abbreviate(30);
            //    }
            //}

            DataSourceResult result = viewModelLessons.ToDataSourceResult(request);

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        // POST: /Administration/Skill/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([DataSourceRequest]DataSourceRequest request, LessonViewModel lessonVM)
        {
            if (ModelState.IsValid)
            {
                var lesson = lessonVM.FillModel(db.Context);
                db.Lessons.Add(lesson);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(new[] { lessonVM }.ToDataSourceResult(request, ModelState));
        }

        // POST: /Administration/Skill/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([DataSourceRequest]DataSourceRequest request)
        {
            Request.InputStream.Seek(0, SeekOrigin.Begin);
            String jsonData = new StreamReader(this.Request.InputStream).ReadToEnd();
            return Content("asdf");
            //if (ModelState.IsValid)
            //{
            //    var model = db.Lessons.GetById(lessonVM.LessonId);
            //    lessonVM.FillModel(db.Context, model);
            //    db.Lessons.Update(model);
            //    return RedirectToAction("Index");
            //}
            //return View(new[] { lessonVM }.ToDataSourceResult(request, ModelState));
        }

        // GET: /Administration/Skill/Delete/5
        public ActionResult Delete([DataSourceRequest]DataSourceRequest request, LessonViewModel lessonVM)
        {
            if (ModelState.IsValid)
            {
                db.Lessons.Delete(lessonVM.LessonId);
            }

            return View(new[] { lessonVM }.ToDataSourceResult(request, ModelState));
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

src/LearningSystem.App/Controllers/ExerciseController.cs
using LearningSystem.App.AppLogic;
using LearningSystem.App.ViewModels;
using LearningSystem.Data;
using LearningSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Http;
using System.Web.Mvc;
using TeamAzureDragon.Utils;

namespace LearningSystem.App.Controllers
{
    public class ExerciseController : LearningSystemControllerBase
    {
        public ExerciseController(IUoWLearningSystem db) : base(db) { }

        private int CountQuestions(int exId)
        {
            int count = Db.Exercises.GetById(exId).Questions.Count;
            return count;
        }

        private QuestionViewModel GetCurrentQuestion(int exId, int toSkip)
        {
            var question = Db.Questions.All("Users")
                .Where(q => q.ExerciseId == exId)
                .OrderBy(q => q.Order)
                .Skip(toSkip)
                .Take(1)
                .Select(q => new QuestionViewModel
                {
                    QuestionId = q.QuestionId,
                    Statement = q.Statement,
                    AnswerType = q.AnswerType,
                    AnswerContent = q.AnswerContent,
                    ExerciseId = q.ExerciseId
                })
                .FirstOrDefault();

            return question;
        }

        public ActionResult Index(int exId)
        {
            var question = GetCurrentQuestion(exId, 0);

            if (question == null)
            {
                return View("_MissingQuestions");
            }

            var handler = AnswerHandlerFactory.GetHandler(question.AnswerType, question.AnswerContent);
            question.InputHtml = handler.RenderInputHtml();

            ViewBag.LessonId = Db.Exercises.GetById(exId).LessonId;
            ViewBag.Lesson = Db.Exercises.GetById(exId);
            ViewBag.CurrentQuestionOrder = 0;
            ViewBag.ExId = exId;
            var questionsCount = this.CountQuestions(exId);
            ViewBag.QuestionsCount = questionsCount;

            var passableErrors = questionsCount / 4;
            if (passableErrors == 0)
	        {
		        passableErrors = 1;
	        }
            ViewBag.PassableErrors = passableErrors;
            return View(question);
        }

        public ActionResult GetQuestion(int exId, int toSkip)
        {
            var question = GetCurrentQuestion(exId, toSkip);

            if (question == null)
            {
                return HttpNotFound();
            }

            var handler = AnswerHandlerFactory.GetHandler(question.AnswerType, question.AnswerContent);
            question.InputHtml = handler.RenderInputHtml();

            return PartialView("_Question", question);
        }

        public ActionResult FinishExercise(int exId)
        {
            //var exercise = Db.Exercises.GetById(exId);

            //var user = Db.Users.All().SingleOrDefault(u => u.UserName == User.Identity.Name);
            //exercise.Users.Add(user);
            //Db.SaveChanges();

            ViewBag.ExId = exId;

            return PartialView("_FinishExercise");
        }

        public ActionResult FailedExercise(int exId)
        {
            ViewBag.ExId = exId;

            return PartialView("_FailedExercise");
        }

        public ActionResult BackToLesson(int exId)
        {
            var exercise = Db.Exercises.GetById(exId);
            var lessonId = exercise.LessonId;
            //TODO check if lesson is finished in the redirected action
            return RedirectToAction("Index", "Lesson", new { lessonId = lessonId });
        }

        [System.Web.Mvc.HttpPostAttribute]
        public ActionResult HandleQuestionInput(int questionId, string input, bool passExercise)
        {
            var question = Db.Questions.GetById(questionId);
            if (question == null)
                throw new HttpResponseException(HttpStatusCode.BadRequest);

            var handler = AnswerHandlerFactory.GetHandler(question.AnswerType, question.AnswerContent);

            var result = handler.ValidateInput(input);

            var dict = Misc.SerializeToDictionary(result);

            /* {
             *  success (bool),
             *  errorContent (string),
             *  exerciseFinished (bool)
             *  lessonFinished (bool),
             *  skillFinished (bool)
             *  }
             */

            if (result.Success || passExercise)
            {
                var exercise = question.Exercise;
                if (question.Order == exercise.Questions.Max(q => q.Order))
                {
                    var user = this.GetCurrentUser();

                    dict["exerciseFinished"] = true;
                    user.Exercises.Add(exercise);

                    var lesson = exercise.Lesson;
                    if (exercise.Order == lesson.Exercises.Max(e => e.Order))
                    {
                        dict["lessonFinished"] = true;
                        user.Lessons.Add(lesson);
                        if (!lesson.Skill.Lessons.Select(l => l.LessonId).Except(user.Lessons.Select(l => l.LessonId)).Any())
                        {
                            dict["skillFinished"] = true;
                        }
                    }

                    Db.SaveChanges();
                }
            }

            return new JsonResult { Data = dict };
        }
    }
}

src/LearningSystem.App/Controllers/LessonController.cs
using LearningSystem.App.ViewModels;
using LearningSystem.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LearningSystem.App.Controllers
{
    [Authorize]
    public class LessonController : Controller
    {
        IUoWLearningSystem db;
        public LessonController(IUoWLearningSystem db)
        {
            this.db = db;
        }
        //
        // GET: /Lesson/
        public ActionResult Index(int lessonId)
        {
            List<ExerciseViewModel> exercises = new List<ExerciseViewModel>();
            var dbEx = db.Exercises.All("Users").Where(ex => ex.LessonId == lessonId).OrderBy(ex => ex.Order);

            bool isAvailable = true;
            foreach (var excercise in dbEx)
            {
                var exerciseVM = new ExerciseViewModel
                {
                    Name = excercise.Name,
                    Description = excercise.Description,
                    ExerciseId = excercise.ExerciseId,
                    IsCompleted = excercise.Users.Any(u => u.UserName == User.Identity.Name) ? true : false,
                    IsAvailable = isAvailable
                };

                if (exerciseVM.IsCompleted == false)
                {
                    isAvailable = false;
                }

                exercises.Add(exerciseVM);
            }

            ViewBag.SkillId = db.Lessons.GetById(lessonId).SkillId;
            ViewBag.Lesson = db.Lessons.GetById(lessonId);
            return View(exercises);
        }
    }
}

src/LearningSystem.App/Areas/Administration/Views/Lesson/Details.cshtml
@model LearningSystem.Models.Lesson

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Lesson</legend>
    <dl>
        <dt>
            @Html.DisplayNameFor(model => model.SkillId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Skill.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Requirements)
        </dt>
        @foreach (var item in Model.Requirements)
        {
            <dd>
                @*@Html.ActionLink(item.Name, "Details", "Lesson", new { id = "LessonId" })*@
                @Html.Label(item.Name)
            </dd>
        }      
        <dt>
            @Html.DisplayNameFor(model => model.Exercises)
         </dt>
        @foreach (var item in Model.Exercises)
        {
            <dd>
                @Html.ActionLink(item.Name, "Details", "Exercise", new { area = "Administration", id = item.ExerciseId }, null)
            </dd>
        }  

    </dl>
</fieldset>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

src/LearningSystem.App/Areas/Administration/Views/Lesson/Index.cshtml
@using TeamAzureDragon.Utils;
@{
    ViewBag.Title = "Administration";
}
<h2>Lessons</h2>
@using (Html.BeginForm())
{
    @(Html.Kendo().Grid<LearningSystem.App.Areas.Administration.ViewModels.LessonViewModel>()
    .Name("Grid")
    .Columns(columns =>
        {
            columns.Bound(l => l.Skill).ClientTemplate("#= data.Skill != null ? data.Skill.Name : '' #").EditorTemplateName("SkillDropdown");
            columns.Bound(l => l.Name);
            columns.Bound(l => l.Description).ClientTemplate("#= abbreviate(data.Description) #");
            //columns.Bound(l => l.Requirements).ClientTemplate("#=generateRequirementTemplate(Requirements)#");//.EditorTemplateName("RequermentCheckBoxList");
            columns.Bound(l => l.Requirements).ClientTemplate("#= generateRequirementTemplate(data.Requirements) #").EditorTemplateName("MultiSelectRequierments");
            columns.Command(commands =>
            {
                commands.Edit();
                commands.Destroy();
                commands.Custom("View Details").Click("showDetails");
                commands.Custom("Exercises").Click("showExercises");
            }).Title("Commands").Width(350);
        })
    .ToolBar(toolbar => toolbar.Create())
    .Editable(editable => editable.Mode(GridEditMode.InLine))//.TemplateName("_LessonTemplate"))
    .DataSource(datasource => datasource
        .Ajax()
        .PageSize(5)
        .ServerOperation(true)
        .Model(model =>
        {
            model.Id(lesson => lesson.LessonId);
            model.Field(lesson => lesson.LessonId).Editable(false);
            //model.Field(lesson => lesson.Requirements).Editable(false);
        })
        .Read(read => read.Action("Read", "Lesson"))
        .Create(create => create.Action("Create", "Lesson"))
        .Update(update => update.Action("Edit", "Lesson"))
        .Destroy(destroy => destroy.Action("Delete", "Lesson"))
    )
    .Pageable()
    .Sortable()    
    )
    @Html.AntiForgeryToken()
}

<script>
    function showDetails(e) {
        e.preventDefault();
        var dataItem = this.dataItem($(e.currentTarget).closest("tr"));
        var url = '@Url.Action("Details", "Lesson", new { id = "_id" })';
        window.location.href = url.replace('_id', dataItem.LessonId);
    }
    function showExercises(e) {
        e.preventDefault();
        var dataItem = this.dataItem($(e.currentTarget).closest("tr"));
        var url = '@Url.Action("Index", "Exercise", new { id = "_id" })';
        window.location.href = url.replace('_id', dataItem.LessonId);
    }
    function generateRequirementTemplate(data) {
        var template = "";
        if (data) {
            for (var i = 0; i < data.length; i++) {
                template = template + data[i].Name + "<br />";
            }
        }
        return template;
    }

    function abbreviate(data) {
        var template = "";
        if (data) {
            if (data.length > 30) {
                template = data.substr(0, 30) + "...";
            }
            else {
                template = data;
            }
        }
        return template;
    }

</script>